---
title: 'Discrete Choice Modelling'
author: admin
date: '2020-11-03'
subtitle: 'Econométrie des variables qualitatives'
summary: ''
authors: [IJ]
lastmod: '2020-11-03'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
link-citations: yes
biblio-style: apalike
bibliography: [data/biblio_SABD.bib]
\nocite: |
 @Greene2008,@Greene2009, @McFaddenTrain2000, @Train2009, @Agresti2013, 
---

# Syllabus

### Course title: Econométrie de variables qualitatives (Econométrie 3)
### Public: Etudiants du M2 C2ES (Chargé d'Etudes Economiques et Statistiques), UGA
### Teachers: Iragaël Joly
### Number of students per year: 10 à 15
### Number of hours per year: 24h/student
### Period : 2016-auj
### Teaching language: français


## Website of the couse

[Discrete Choice Modelling](https://discretchoicemodelling.netlify.app/)


## Description: 

This course introduces the statistical and econometric tools specific to the processing of categorical variables. It aims to present methods that can be used in business, for example odd-ratio type indicators and tests, classical logistic regression. It brings M2 students to approach the tools used in research within the framework of discrete choice model by providing multinomial logit type models and its extensions: nested logit model, latent class logit, mixed logit.

## Course Objectives:

The objective of the course is to present and apply econometric methods for modeling qualitative variables and discrete choices. The former are suitable for modeling qualitative outcomes, ordered or not (eg: logit and probit models). Discrete choice models are used for the disaggregated study of individual consumption behaviors and the study of demand. 

These methods make it possible, for example, to estimate and predict market shares between different products, willingness to pay for a product or for a specific attribute. This course will come back to the concepts of consumer surplus and to the solutions to estimate them.

Particular attention is given to the interpretation of the results and the method of construction of the model. In particular, the realization of a tutored project on a database resulting from my research leads the students to manage their analysis of an urban mobility issue by structuring it on the relevant literature and to build a model in a critical and argued manner.

## Educational Approach : 

This course is an applied course using R and RStudio software. One explicit desire and expectation of the course is the production of reproducible and transparent work using RStudio. The different analytical techniques are presented and applied through exercises and through a semester project that is the subject of a defense to prepare for writing a report.

## References

